{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.tomato",
    "module": "tinyjson-annotations",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tinyjson-annotations-1.0.0.jar",
          "url": "tinyjson-annotations-1.0.0.jar",
          "size": 2249,
          "sha512": "e8ce2389d73121857363b2c5e4694e72e8888f84c3376f72d2ebca4a7fc4973657659bef672c24e2e7322b23411d9a7e46c6577fead5d5714080e721460fd3e4",
          "sha256": "69aa7886a50304eb62b6b903da070b1c7e45369ea2f0e960ffcbcbc6f8635ffc",
          "sha1": "8019a7cf5a455ed86b487e0fad26a26841f931cb",
          "md5": "d04fb3f28f0acee62ce0d70bf4cbd47f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "tinyjson-annotations-1.0.0.jar",
          "url": "tinyjson-annotations-1.0.0.jar",
          "size": 2249,
          "sha512": "e8ce2389d73121857363b2c5e4694e72e8888f84c3376f72d2ebca4a7fc4973657659bef672c24e2e7322b23411d9a7e46c6577fead5d5714080e721460fd3e4",
          "sha256": "69aa7886a50304eb62b6b903da070b1c7e45369ea2f0e960ffcbcbc6f8635ffc",
          "sha1": "8019a7cf5a455ed86b487e0fad26a26841f931cb",
          "md5": "d04fb3f28f0acee62ce0d70bf4cbd47f"
        }
      ]
    }
  ]
}
