{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.tomato",
    "module": "tinyjson-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tinyjson-plugin-1.0.0.jar",
          "url": "tinyjson-plugin-1.0.0.jar",
          "size": 2237,
          "sha512": "7569a1235c301852b0a250ca7477dea699458396f6af2285da6176a31ca74977aef118749b82030f848a53b5a1f5068132eb6086547fa106ecf83f86af8c347f",
          "sha256": "47e03fc95c75048b2b1c5e09a3b552295945dfad9ac99b1df814103a61559e03",
          "sha1": "b3da8d0e145db54162eadad7f0652eccc6822b96",
          "md5": "d4eb7f0ccbeee934fe627ab1ded8caf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "tinyjson-plugin-1.0.0.jar",
          "url": "tinyjson-plugin-1.0.0.jar",
          "size": 2237,
          "sha512": "7569a1235c301852b0a250ca7477dea699458396f6af2285da6176a31ca74977aef118749b82030f848a53b5a1f5068132eb6086547fa106ecf83f86af8c347f",
          "sha256": "47e03fc95c75048b2b1c5e09a3b552295945dfad9ac99b1df814103a61559e03",
          "sha1": "b3da8d0e145db54162eadad7f0652eccc6822b96",
          "md5": "d4eb7f0ccbeee934fe627ab1ded8caf5"
        }
      ]
    }
  ]
}
